### ISSUE TITLE
Should use project config rather than parsing the aquifer.json file again

### ISSUE THREAD

**Issue by chasingmaxwell** [aquifer/aquifer-artifact#2]
We already have access to project config (including paths) like this:
Aquifer.project.config.paths...

You can see this being done in aquifer here:
https://github.com/aquifer/aquifer/blob/36b1f974a70a44196a6c2e8482bf0ca2be2f255a/lib/build.command.js#L25

Here's where the aquifer.json file is being parsed in aquifer-artifact:
https://github.com/aquifer/aquifer-artifact/blob/master/bin/index.js#L33

There's an issue for this on aquifer-git as well here: https://github.com/aquifer/aquifer-git/issues/4

**Comment by fluxsauce** [comment]
Thanks!
